### ISSUE TITLE
L12: NPE

### ISSUE THREAD

**Issue by hohwille** [devonfw/sonar-devon4j-plugin#12]
```
[ERROR] Unable to run check class com.devonfw.ide.sonarqube.common.impl.check.DevonArchitectureLayerDataaccess2LogicCheck - Devon4j:L12 on file /projects/.../....java, To help improve SonarJava, please report this problem to SonarSource : see https://www.sonarqube.org/community/
java.lang.NullPointerException: null
	at com.devonfw.ide.sonarqube.common.impl.check.DevonArchitectureCheck.visitClass(DevonArchitectureCheck.java:99)
```

**Comment by hohwille** [comment]
https://github.com/devonfw/sonar-devon-plugin/blob/881ea7b8b35c7dedf5afc613cea78be22369f331/src/main/java/com/devonfw/ide/sonarqube/common/impl/check/DevonArchitectureCheck.java#L99

**Comment by hohwille** [comment]
@lmarniazman can you have a look here? Is that issue still present. Should be easy to fix in a few minutes...

**Comment by lmarniazman** [comment]
Hi Jörg, sure I'll look into it. How can I produce this error? Just so I can test my solution.

**Comment by hohwille** [comment]
It is still present here:
https://github.com/devonfw/sonar-devon4j-plugin/blob/master/src/main/java/com/devonfw/ide/sonarqube/common/impl/check/DevonArchitectureCheck.java#L99

I can not say for sure how I produced this error. If `simpleName()` returns `null` I assume it must have been an annonymous inner class. You can try to reproduce it but otherwise you might just fix the NPE blindly as a trivial if else should already do. IMHO it would be safe to set local variable `simpleName` to the empty `String` (`""`) in case that `simpleName()` returned `null`.
This is the last issue for our milestone of release `3.2.0`. It would be awesome, if you could fix this today as I am currently at the airport on my way out.

**Comment by hohwille** [comment]
Done with PR #36
