### ISSUE TITLE
Filtering support via tag

### ISSUE THREAD

**Issue by hohwille** [devonfw/sonar-devon4j-plugin#13]
With sonar qube you can do nice drill downs in the issues. The key feature are the five severities that are very helpful.
When searching for rules you can filter by repository. However, for issues this is not possible. However, an option for filtering is via tags. So in case you want to filter to rules of this plugin an option could be to tag all created issues with `architecture` or even more specific with `devon`.

**Comment by lmarniazman** [comment]
See Issue #18, fixed by #20

**Comment by hohwille** [comment]
So now all our rules are tagged with `architecture-violation`. Additionally a tag `devonfw` could still be helpful. Additionally our sub-packages `layer`, `thirdparty`, `component`, `packaging` should also be added as tags. Then you can better filter via tags. Should be easy to fix this issue within some minutes.

**Comment by hohwille** [comment]
Done with PR #35
