### ISSUE TITLE
devon layer violation rule hitting on Cobigen generated code

### ISSUE THREAD

**Issue by rhobolic** [devonfw/sonar-devon4j-plugin#138]
**Problem**
When I generate the code in Cobigen and then it passes SonarQube the devon for layer violation is hit. 
![image](https://user-images.githubusercontent.com/99953472/171180619-30c1bc03-1222-4f93-835a-de454e5de0c8.png)
It is importing the *SearchCriteriaTo.java in the Repository

**Expected behavior**
There is no layer violation caused by Cobigen generated code at all

**Comment by hohwille** [comment]
I created this issue in CobiGen https://github.com/devonfw/cobigen/issues/1548 and hence close this issue as `sonar-devon4j-plugin` behaves correct here.
