### ISSUE TITLE
Install devon4j quality profile

### ISSUE THREAD

**Issue by hohwille** [devonfw/sonar-devon4j-plugin#16]
Devon brings quality profiles for devon projects:
https://github.com/devonfw/devon-ide/tree/master/settings/src/main/settings/sonarqube/profiles

These are currently work in progress but are evolving now. The sonar-devon-plugin should automatically install them into SonarQube. 
In case of an update or a re-installation of the plugin we need to clarify if:

. the quality profile is overwritten
. the quality profile is only created if it does not exist

In the first option the profile is always up-to-date and can also include new rules introduced with a newer version on update. The drawback is that customizations to the quality profile would be lost (overwritten). Therefore users would need to know that they have to clone the profile to make their own customization.

**Comment by lmarniazman** [comment]
Regarding your question: As far as I know, a built in profile is not customizable, so users would have to create a copy of our profile anyway to make their own custom profile with other active rules. I think overwriting the quality profile with every new version of our plugin is not a problem in this case.

**Comment by hohwille** [comment]
Thanks @lmarniazman 👍 
Agreed. So users would use the "standard" or have to create their own "copy" that is then not touched anymore on updates. However, when you create the "copy" you get all from the standard and after an update you could also compare the "copy" with the updated "standard" so all should be fine.

**Comment by lmarniazman** [comment]
From the standard Java rules directly from Sonar (squid repository), there currently are five that are either deprecated or only available in the commercial version of SonarQube:

* S2076
* S2078
* S3318
* S4142
* S2070

I will leave them in the xml for now, but exclude them when creating the profile. We can then discuss what to do with them.

**Comment by hohwille** [comment]
Was fixed with #56 so closing this issue.
