### ISSUE TITLE
Rework issues from sonarsource.io

### ISSUE THREAD

**Issue by hohwille** [devonfw/sonar-devon4j-plugin#41]
With #40 we are now analyzing our own plugin code. The issues found by SonarQube should be analysed and reworked where possible/makes sense (e.g. remove outcommented code, get rid of System.out).
https://sonarcloud.io/project/issues?id=devonfw_sonar-devon4j-plugin&resolved=false&types=CODE_SMELL

**Comment by lmarniazman** [comment]
What about the 'bugs' shown in the analysis?

**Comment by lmarniazman** [comment]
About half of the code smells have been fixed with PR #50, so the quality gate is green now. However, there are still seven code smells and three bugs open, so I will look into fixing them in a seperate PR.

**Comment by hohwille** [comment]
3 bugs left:
* [ ] [tree may be null](https://sonarcloud.io/project/issues?id=devonfw_sonar-devon4j-plugin&open=AW3t44bR-dJmagWAQnZO&resolved=false&types=BUG) - valid point. Just add `null` check and return immediately in that case.
* [ ] [tree may be null 2](https://sonarcloud.io/project/issues?id=devonfw_sonar-devon4j-plugin&open=AW3t44an-dJmagWAQnZK&resolved=false&types=BUG) - same problem
* [ ] [getter and property mismatch](https://sonarcloud.io/project/issues?id=devonfw_sonar-devon4j-plugin&open=AW3t44Yo-dJmagWAQnZH&resolved=false&types=BUG) - actually intended. However if that would be the last remaining but, why not renaming the fields accordingly (`errors` -> `errorsMutable` and `errorsView` -> `errors`)  to make SonarQube happy.

**Comment by lmarniazman** [comment]
As far as I can see, there already is a null check for the two NPE. I added an `if(this.tree == null) {return;}` after a call of `getTreeInstance(context);`

**Comment by hohwille** [comment]
IMHO all done and issue can be closed. Correct or am I missing something?

**Comment by lmarniazman** [comment]
Yes, all done and can be closed.

**Comment by hohwille** [comment]
All fixed now, hence closing.
