### ISSUE TITLE
Publish to SonarQube marketplace

### ISSUE THREAD

**Issue by hohwille** [devonfw/sonar-devon4j-plugin#5]
Updated link:
https://community.sonarsource.com/t/new-plugin-publish-sonar-devon4j-plugin-to-marketplace/15633

https://docs.sonarqube.org/7.4/instance-administration/marketplace/
https://community.sonarsource.com/t/publish-to-marketplace/5045

**Comment by hohwille** [comment]
New feedback:
* [ ] Document releases on github. Done: https://github.com/devonfw/sonar-devon4j-plugin/releases
* [ ] #40: enable sonarcloud.io
* [ ] Submit metadata PR: https://github.com/SonarSource/sonar-update-center-properties

**Comment by hohwille** [comment]
We need to create a PR to https://github.com/SonarSource/sonar-update-center-properties.
I think we need to create `devon4j.properties` there with such content:
```
category=Governance
description=validate devon4j architecture and conventions.
homepageUrl=https://github.com/devonfw/sonar-devon4j-plugin/#sonar-devon4j-plugin
archivedVersions=
publicVersions=3.2.0

defaults.mavenGroupId=com.devonfw.tools
defaults.mavenArtifactId=sonar-devon4j-plugin

3.2.0.description=First official release und the name sonar-devon4j-plugin.
3.2.0.sqVersions=[6.4,7.*]
3.2.0.downloadUrl=https://repo.maven.apache.org/maven2/com/devonfw/tools/sonar-devon4j-plugin/3.2.0/sonar-devon4j-plugin-3.2.0.jar
3.2.0.date=2019-10-18
3.2.0.changelogUrl=https://github.com/devonfw/sonar-devon4j-plugin/blob/master/CHANGELOG.adoc#320
```

We should consider completing #42 and create a new release before going to marketplace as we also changed the `pluginKey` what could cause problems. Therefore the information above will need an update to the new release once published.

**Comment by lmarniazman** [comment]
PR to sonar-update-center: https://github.com/SonarSource/sonar-update-center-properties/pull/78
New topic in forum: https://community.sonarsource.com/t/new-release-sonar-devon4j-plugin-3-2-1/17962

**Comment by hohwille** [comment]
@lmarniazman 👍 👍 👍 thanks for your great support. We have made it to the official marketplace.
