### ISSUE TITLE
Rethink module declaration

### ISSUE THREAD

**Issue by lmarniazman** [devonfw/sonar-devon4j-plugin#52]
As of Java 9, there has been the introduction of the module-info.java. Maybe we could make use of that and make the users of our plugin declare their modules there? 

It would make things easier for them, as some of them may already have their modules declared this way and don't need to create a new architecture.json, which would just contain redundant info. 
It could also make things easier for us as we could use the new API around this module declaration feature.

What do you think, @hohwille?

**Comment by hohwille** [comment]
This is generally a nice idea. However, adoption for `module-info` is going very slightly in the Java ecosystem. Once introduced it turns a regular classpath JAR into a module for the module path with severe implications:
* can not run in JVM <= 1.8
* reflection no more available (unless explicity configured/allowed)
* split packages stricktly forbidden (two modules can not have code in the same package - this was not the case for regular JARs and would force several Java libs to introduce breaking changes moving code to other packages).
* ServiceLoader changed and configuration has to be migrated to `module-info` (from `META-INF`)
* I18N changed

As we are mainly addressing spring apps and those will currently have no chance to run properly with modules, I do not see that we are ready for this. I will even close this to prevent stale issues and when the time has come some day, we can reopen or create a new issue.
*
