### ISSUE TITLE
Bug in DevonNamingConventionClassExtendsClassUcImplCheck.isImplementingCorrectInterface

### ISSUE THREAD

**Issue by hohwille** [devonfw/sonar-devon4j-plugin#60]
In PR #50 I found a small bug in `DevonNamingConventionClassExtendsClassUcImplCheck.isImplementingCorrectInterface` after merging:

```
protected boolean isImplementingCorrectInterface(String superInterface) {
    boolean isImplementingCorrectInterface = false;
    for (String name : this.superInterfacesNames) {
      if (superInterface.equals(name)) {
        return true;
      } else {
        return false;
      }
      isImplementingCorrectInterface = superInterface.equals(name);
    }
    return isImplementingCorrectInterface;
}
```

> actually this was wrong before and still is wrong.
If superInterface.equals(name) is true this method should return true. Currently it only does if the expected interface is the last one.

**Comment by lmarniazman** [comment]
Fixed with PR #63, can be closed.
