### ISSUE TITLE
Whole body of method / class is marked as an issue location

### ISSUE THREAD

**Issue by lmarniazman** [devonfw/sonar-devon4j-plugin#67]
From a comment on the release of our plugin on the marketplace: 

> For class- and method-level issues, you’ve marked the entire body of the class/method as the issue location. This has the disadvantage of a) being irritating, b) putting your issue message at the bottom of a potentially long block of relevant(?) text. E.G.
> ![Selection_841](https://user-images.githubusercontent.com/49903872/73477029-c1dd9800-4393-11ea-98f8-fe11a17c27f4.jpg)
> ![Selection_842](https://user-images.githubusercontent.com/49903872/73477035-c4d88880-4393-11ea-8a9f-ea98c1c92faf.jpg)
> I suggest instead you only use the name/declaration as the issue location.

I agree that it is a good idea to only mark the class declaration or method header in case of a violation that affects the whole class or method.

**Comment by hohwille** [comment]
Fixed with PR #70
