### ISSUE TITLE
Colors in rule descriptions are not accessible for colorblind people

### ISSUE THREAD

**Issue by lmarniazman** [devonfw/sonar-devon4j-plugin#68]
In version 3.2.1, we added rule descriptions, where certain code parts in examples are marked red or green. We should change the coloring here to make it readable for people with color blindness.

**Comment by hohwille** [comment]
Aren't there default CSS styles for that in SonarQube that we can use?
Otherwise have a look at official SQ java plugin (squid) and use the same colors/style...

**Comment by lmarniazman** [comment]
As far as I can see, the descriptions of the original SQ java rules don't have any coloring. Maybe we can keep the coloring as it is and add other visual cues, e.g. crossed out code when noncompliant.

**Comment by lmarniazman** [comment]
I now changed compliant / noncompliant code to blue / yellow with the addition of compliant parts being underlined and noncompliant parts being striked through. I'll raise a PR shortly so you can take a look.

***Hex Codes used for coloring***
* Underlines / Strikethrough: #979696 (light grey)
* Compliant code: #648FFF (blue)
* Noncompliant code: #FFB000

**Comment by hohwille** [comment]
fixed with PR #69
