### ISSUE TITLE
NPE when analyzing certain files

### ISSUE THREAD

**Issue by lmarniazman** [devonfw/sonar-devon4j-plugin#71]
In our thread on the release of the plugin on the marketplace, there was following comment: https://community.sonarsource.com/t/new-release-sonar-devon4j-plugin-3-2-1/17962/9?u=lmarniazman

It said that there are a lot of NPEs thrown when trying to run an analysis on files not directly related to devon4j.

**Comment by hohwille** [comment]
Fixed with PR #72
