### ISSUE TITLE
Increase code coverage of tests

### ISSUE THREAD

**Issue by lmarniazman** [devonfw/sonar-devon4j-plugin#73]
Especially on checks that are not just a simple comparison of dependencies, but have a lot of logic embedded into them (like the Hibernate check or the naming checks), some more code coverage would be beneficial. 
Issues like #71 could be avoided that way.

**Comment by lmarniazman** [comment]
I extended this issue to generally cleaning up the test files a little. I organized them so that every test is for one specific use-case and doesn't contain both noncompliant and compliant code. That way most of the if-branches are looked into.

**Comment by hohwille** [comment]
Done with PR #79
