### ISSUE TITLE
Refactoring of Quality Profiles due to changes in Sonar Java Analyzer v6.0

### ISSUE THREAD

**Issue by lmarniazman** [devonfw/sonar-devon4j-plugin#76]
With the 6.0 version of the Sonar Java Analyzer, the repository key for Sonar rules changed from "squid" to "java". We will need to refactor those keys in our quality profile declaration.
Also rule S3340 was taken out, so that should either be dropped from the xml or filtered out during the profile creation.
Rule S1188 was split into S1188 and S5612, so we will have to think about whether we need this new S5612 and include it in the xml.

More information here: 
* [Release notes of Java analyzer v6.0](https://community.sonarsource.com/t/java-analyzer-v6-0-more-accurate-analysis-with-fewer-false-positives/18547)
* [Thread asking about getting information during server startup (i.e. which version of the Java analyzer is active on the server)](https://community.sonarsource.com/t/getting-information-during-server-startup/21464)

**Comment by lmarniazman** [comment]
**Deprecated** -> **Replacement**
  S2258, S2278  ->          S5547
       S2277         ->          S5542

**Comment by lmarniazman** [comment]
See PR #56

**Comment by lmarniazman** [comment]
There was an answer from the SonarQube team for this issue:
They support basic HTML without style information in their rule description. There is currently no plan to add styling.
For the full answer, see the topic referenced in the original issue text.

**Comment by lmarniazman** [comment]
Further rules that have been deprecated and need to be removed / replaced:

* S3027
* S2391
* S1148

**Comment by hohwille** [comment]
@lmarniazman can you clarify the status of this issue?
IMHO it has already been fixed with PR #56. Thereforee, the milestone should be `2020.08.001` and the issue should bee closed. Correct?

**Comment by hohwille** [comment]
Closing as agreed with @lmarniazman
