### ISSUE TITLE
Redundancy of Code

### ISSUE THREAD

**Issue by lmarniazman** [devonfw/sonar-devon4j-plugin#81]
This is a follow up for Issue #71, which was first fixed with PR #72.
The bug was simply a NPE being thrown when a check was trying to parse a `ClassTree` from a file that didn't contain any class.
The fix was an if-condition inside `scanFile()` (where this parse happens) checking if the file that is currently being analyzed contains a class.

Comment by @hohwille:

> @lmarniazman thanks for the fix +1
> Did you put this redundantly into all implementations of `scanFile`? Are their cases/rules where we want to proceed even if `tree` is null?
> If there is no case where we want to do anything if `tree` is `null` we should IMHO refactor our code:
> Implement `scanFile` method with `final` modifier in our topmost abstract rule class.
> Get the `tree` and only if not `null` call a new protected method `doScanFile(ClassTree, Context)` that is then implemented instead by sub-classes. WDYT?
> If I am mistaken we can approve. Your solution looks fine - I am just thinking if there is a simple fix to improve the code quality...

Currently there are three cases, where an implementation of `scanFile()` is needed. All three of them require the currently analyzed file to contain a class:

1. Naming convention checks for interfaces
2. Naming convention checks for classes

Kind of self-explanatory, if there is no class or interface, there is also no class or interface name to check.

3. Check for the correct annotation of Use-Case implementation methods

This of course requires a class as well, because we are looking for methods. If there is none, there is no need to proceed with the check either.

Therefore a method in the superclass `DevonArchitectureCheck` would be a better option, implemented as described in the comment above.

The second redundancy is related to this issue, as each class that falls into one of these three use-cases, contains their own method which parses the `ClassTree`. As they do exactly the same thing (completely the same, line for line, only different names), this could simply be put into the superclass and made available to its subclasses that way.

**Comment by hohwille** [comment]
Done with PR #84
