### ISSUE TITLE
update to maven-parent

### ISSUE THREAD

**Issue by hohwille** [devonfw/sonar-devon4j-plugin#83]
As a maintainer of devonfw, I want repositories using maven builds to make use of devonfw's `maven-parent` so that configs, settings, plugin-versions, etc. are standardized across devonfw and we can avoid redundancies.

**Comment by lmarniazman** [comment]
Could this be closed since PR #86 has been merged?

**Comment by hohwille** [comment]
Jep. Done with PR #86
