### ISSUE TITLE
Display warnings on the 'devonfw' config page in the 'Administration' section of SonarQube

### ISSUE THREAD

**Issue by lmarniazman** [devonfw/sonar-devon4j-plugin#92]
As a SonarQube instance admin, I want to see a warning displayed on the devonfw config page if their Quality Profile could not be initialized because of missing plugins, so that I can install those plugins.

**Comment by hohwille** [comment]
thanks @lmarniazman  for creating this issue. We will see if we can include this into `2020.08.001` release or not.

**Comment by hohwille** [comment]
See also issue #110 - IMHO this warning feature is still valuable as people might remove plugins afterwards or may manually add/remove plugins in the `extensions` folder.

**Comment by hohwille** [comment]
Done with PR #115
