### ISSUE TITLE
Custom configuration for architecture

### ISSUE THREAD

**Issue by hohwille** [devonfw/sonar-devon4j-plugin#97]
In sonar-devon4j-plugin we are using `Devon4jPackage` to parse packages and derive architecture infomation (component, layer, scope). This is perfectly fine for `devon4j` projects and support for `devon4j` architecture checks with zero configuration shall obviously be kept.
However, it would be awesome for projects not exactly following `devon4j` architecture to be able to configure the architecture to overrule the default `devon4j` architecture.
This should be done in `architecture.json` file like this:
```
{
  "architecture": {
    "packages": {
        "pattern": "([a-zA-Z0-9_]+\.)+(persistence|core|service|gui)\.([a-zA-Z0-9_]+)\.(api|base|impl)(\.[a-zA-Z0-9_]+)*",
        "groups": [ "root", "layer", "component", "scope", "detail" ],
        "mappings": {  "persistence": "dataaccess", "core": "logic", "gui": "client"}
    }
  }
}
```
The `pattern` is the regular expression to match the package.
The `groups` map the groups of the regex to specifc functions. You may additionally use any other group-id here to ignore a group (e.g. in case of nested paranthesis).
With `mappings` custom names for layers, scopes, or even components (like `general` or `app`) can be mapped to `devon4j` standards in order to be understood properly.

**Comment by hohwille** [comment]
For implementation a first step should be to encapsulare or even remove the usage of `Devon4jPackage` without changing the current behaviour.

A next step (maybe separate PR) would be to change the defaults as configured in `architecture.json` like described above.

**Comment by hohwille** [comment]
To get started some hints to find the right spots in the code:
* config needs to be added here: https://github.com/devonfw/sonar-devon4j-plugin/blob/master/src/main/java/com/devonfw/ide/sonarqube/common/api/config/Architecture.java
* Devon4jPackage is created here and passed arround pretty much to every other rule: https://github.com/devonfw/sonar-devon4j-plugin/blob/master/src/main/java/com/devonfw/ide/sonarqube/common/impl/check/DevonArchitectureCheck.java#L164
* See also here: https://github.com/devonfw/sonar-devon4j-plugin/blob/master/src/main/java/com/devonfw/ide/sonarqube/common/impl/check/DevonArchitectureCheck.java#L33
* As you can see there are various methods used on this current `Devon4jPackage` like here: https://github.com/devonfw/sonar-devon4j-plugin/blob/master/src/main/java/com/devonfw/ide/sonarqube/common/impl/check/DevonArchitectureCheck.java#L190
* So my suggestion would be to define a new class `DevonArchitecturePackage` as a kind of "wrapper" for `Devon4jPackage` that offers the same API methods and delegates them to an internal `Devon4jPackage` instance. Could you create a PR for this as a first step?

**Comment by hohwille** [comment]
I have assigned @suvmanda several devon4j issues. Since he was busy with other tasks and has not started with this issue, it can go back to backlog and be addressed by sonar plugin team.

**Comment by hohwille** [comment]
@adprus are you working on this? If so please assing yourself.

**Comment by lmarniazman** [comment]
Finished with PR [#106](https://github.com/devonfw/sonar-devon4j-plugin/pull/106) and [#107](https://github.com/devonfw/sonar-devon4j-plugin/pull/107)

**Comment by hohwille** [comment]
It was wrong to close this issue as the feature is still not implemented. As you can see still the Devon4jPackage is used internally (also this class has no javadoc and will not match our code-style and might fail in sonarcloud check as well):
https://github.com/devonfw/sonar-devon4j-plugin/blob/master/src/main/java/com/devonfw/ide/sonarqube/common/api/config/DevonArchitecturePackage.java#L5

We have only prepated the feature but it still needs to be implemented.
@lmarniazman could you take this over as the people working on this are no more available.
Change this code-line:
https://github.com/devonfw/sonar-devon4j-plugin/blob/master/src/main/java/com/devonfw/ide/sonarqube/common/impl/check/DevonArchitectureCheck.java#L222

And instead use this method to get the configuration:
https://github.com/devonfw/sonar-devon4j-plugin/blob/master/src/main/java/com/devonfw/ide/sonarqube/common/api/config/Architecture.java#L88

and pass the resulting `Packages` instance as additional argument here:
https://github.com/devonfw/sonar-devon4j-plugin/blob/master/src/main/java/com/devonfw/ide/sonarqube/common/api/config/DevonArchitecturePackage.java#L9

Then as a final step, kick out `Devon4jPackage` and reimplement the required (!) methods of `DevonArchitecturePackage` based on the `Packages` instance. You can remove all unused methods from `DevonArchitecturePackage`.

**Comment by hohwille** [comment]
Finally done with all PRs merged.
